# Generated by Django 3.0.6 on 2020-05-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200530_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_data',
            field=models.TextField(null=True),
        ),
    ]
